-- =============================================================
-- GastroMundi — Schema de referência (estado REAL de produção)
--
-- Reconstruído em 2026-07-04 a partir do banco de produção
-- (information_schema + pg_catalog, projeto jgdvylwiuqgjtavffguc).
-- NÃO edite à mão: mudanças de schema nascem em supabase/migrations/
-- e este arquivo deve ser atualizado junto (ou regenerado via
-- `supabase db dump -f supabase/schema.sql --schema public`,
-- que requer Docker).
--
-- Convenções de RLS (migração 20240107_rls_por_role.sql, claim
-- corrigido em 20260722_fix_jwt_role_claim_v2.sql):
--   auth.role() = 'authenticated'                          → qualquer usuário logado
--   (auth.jwt() -> 'app_metadata' ->> 'gastro_role')        → 'admin' | 'gerente' | 'caixa' | 'garcom'
--   NUNCA usar (auth.jwt() ->> 'role') para o papel do app — a raiz
--   `role` do JWT é reservada pelo PostgREST pro role do banco
--   (sempre 'authenticated'); o papel de negócio só existe em
--   app_metadata.gastro_role, injetado pelo custom_access_token_hook
--   (20240105/20240108) a partir de public.users.
-- =============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ── users (papéis e vínculo com Supabase Auth) ────────────────
-- Senhas vivem SOMENTE em auth.users (coluna password foi removida
-- na migração 20240107; credenciais legíveis removidas em 20260704).
CREATE TABLE public.users (
  id       bigint  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name     text    NOT NULL,
  username text    NOT NULL UNIQUE,
  role     text    NOT NULL,
  active   boolean NOT NULL DEFAULT true,
  auth_id  uuid    UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL
);

-- ── products ──────────────────────────────────────────────────
-- (SEM as colunas legadas unidade_compra/fator_compra_estoque/
--  detalhamento_compra que a versão antiga deste arquivo listava)
CREATE TABLE public.products (
  id                    bigint  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name                  text    NOT NULL,
  price                 numeric NOT NULL,
  category              text    NOT NULL,
  emoji                 text,
  active                boolean NOT NULL DEFAULT true,
  unidades_compra       jsonb   NOT NULL DEFAULT '[]',
  unidade_estoque       text    NOT NULL DEFAULT 'un',
  unidade_consumo       text,
  fator_consumo_estoque numeric DEFAULT 1,
  produzivel            boolean NOT NULL DEFAULT true -- F015, 20260721_produtos_produzivel.sql
);

-- ── pending (pedidos em aberto — Realtime habilitado) ─────────
CREATE TABLE public.pending (
  id         text  PRIMARY KEY,
  comanda    text,
  items      jsonb NOT NULL DEFAULT '[]',
  status     text  NOT NULL DEFAULT 'open',
  note       text,
  total      numeric,
  garcom     text,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  mesa       text,
  apelido    text
);

-- ── sales (vendas finalizadas — payload JSONB; ver TD009) ─────
-- TD009 etapa 2: sales mantida como gravação de backup (dual-write).
-- O app já NÃO lê mais daqui — leituras vêm de vendas/venda_itens/venda_pagamentos.
CREATE TABLE public.sales (
  id   text  PRIMARY KEY,
  data jsonb NOT NULL DEFAULT '{}',
  at   timestamptz NOT NULL DEFAULT now()
);

-- ── vendas / venda_itens / venda_pagamentos ───────────────────
-- TD009 etapa 1 — gravação dupla (supabase/migrations/20260707_vendas_normalizadas.sql).
-- TD009 etapa 2 (supabase/migrations/20260708_backfill_vendas.sql) — backfill
-- do histórico e inversão da fonte de verdade: as LEITURAS (bootstrap do
-- AppContext, assistente do Jarvas) agora vêm destas tabelas; sales
-- segue recebendo a gravação dupla como backup até uma futura etapa 3.
CREATE TABLE public.vendas (
  id           text        PRIMARY KEY,
  comanda      text,
  mesa         text,
  subtotal     numeric,
  taxa_servico boolean     NOT NULL DEFAULT false,
  valor_taxa   numeric     NOT NULL DEFAULT 0,
  valor_ajuste numeric     NOT NULL DEFAULT 0,
  total        numeric     NOT NULL,
  cashier      text,
  cliente_id   uuid        REFERENCES public.clientes(id) ON DELETE SET NULL, -- F010, 20260713_clientes.sql
  at           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.venda_itens (
  id                  uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  venda_id            text    NOT NULL REFERENCES public.vendas(id) ON DELETE CASCADE,
  product_id          bigint  REFERENCES public.products(id) ON DELETE SET NULL,
  nome                text    NOT NULL,
  preco               numeric NOT NULL,
  qtd                 numeric NOT NULL DEFAULT 1,
  cancelado           boolean NOT NULL DEFAULT false,
  motivo_cancelamento text,
  cancelado_por       text
);
CREATE INDEX venda_itens_venda_id_idx   ON public.venda_itens (venda_id);
CREATE INDEX venda_itens_product_id_idx ON public.venda_itens (product_id);

CREATE TABLE public.venda_pagamentos (
  id       uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  venda_id text    NOT NULL REFERENCES public.vendas(id) ON DELETE CASCADE,
  metodo   text    NOT NULL,
  valor    numeric NOT NULL
);
CREATE INDEX venda_pagamentos_venda_id_idx ON public.venda_pagamentos (venda_id);
CREATE INDEX venda_pagamentos_metodo_idx   ON public.venda_pagamentos (metodo);
CREATE INDEX vendas_at_idx ON public.vendas (at DESC);

-- ── lancamentos (Financeiro fase 1 — docs/03_REGRAS_DE_NEGOCIO/FINANCEIRO.md) ──
-- Receita automática nasce de venda.finalizada (por pagamento); fiado
-- vira conta a receber (status 'previsto'). NÃO inclui nesta fase:
-- estorno/reversão, margem por custo de estoque, DRE, centros de custo.
CREATE TABLE public.lancamentos (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  tipo        text        NOT NULL CHECK (tipo IN ('receita', 'despesa')),
  categoria   text        NOT NULL,
  descricao   text,
  valor       numeric     NOT NULL CHECK (valor > 0),
  competencia date        NOT NULL,
  vencimento  date,
  status      text        NOT NULL DEFAULT 'previsto' CHECK (status IN ('previsto', 'pago', 'recebido', 'vencido')),
  origem      text        NOT NULL DEFAULT 'manual' CHECK (origem IN ('venda', 'manual', 'estoque')),
  venda_id    text        REFERENCES public.vendas(id) ON DELETE SET NULL,
  cliente_id  uuid        REFERENCES public.clientes(id) ON DELETE SET NULL, -- F010, 20260713_clientes.sql
  retroativo  boolean     NOT NULL DEFAULT false,
  criado_por  text,
  baixado_por text,
  baixado_em  timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX lancamentos_competencia_idx ON public.lancamentos (competencia);
CREATE INDEX lancamentos_status_idx      ON public.lancamentos (status);
CREATE INDEX lancamentos_tipo_idx         ON public.lancamentos (tipo);
CREATE INDEX lancamentos_venda_id_idx     ON public.lancamentos (venda_id);
CREATE INDEX lancamentos_cliente_id_idx   ON public.lancamentos (cliente_id);

-- ── clientes (F010 — docs/03_REGRAS_DE_NEGOCIO/CLIENTES.md) ───
-- Cadastro, histórico de compras (via vendas.cliente_id) e fiado
-- (via lancamentos.cliente_id — o fiado em si já existe como conta a
-- receber no Financeiro; esta tabela só acrescenta o vínculo).
CREATE TABLE public.clientes (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  nome         text        NOT NULL,
  telefone     text,
  endereco     text,
  observacoes  text,
  anonimizado  boolean     NOT NULL DEFAULT false,
  criado_por   text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX clientes_nome_idx     ON public.clientes (nome);
CREATE INDEX clientes_telefone_idx ON public.clientes (telefone);

-- ── fechamentos ───────────────────────────────────────────────
CREATE TABLE public.fechamentos (
  id         bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  data       jsonb  NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ── config (chave/valor de configurações do caixa) ────────────
-- Keys atuais: fundo_atual, caixa_aberto, sessao_aberta_em,
-- meios_pagamento, taxa_servico, metodos_custom.
-- (keys 'credentials' e 'estoque' foram removidas — 20260704/20260705)
CREATE TABLE public.config (
  key   text  PRIMARY KEY,
  value jsonb NOT NULL
);

-- ── operator_logs (auditoria fire-and-forget) ─────────────────
CREATE TABLE public.operator_logs (
  id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  operator_id text   NOT NULL,
  action_type text   NOT NULL,
  payload     jsonb,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX operator_logs_operator_id_idx ON public.operator_logs (operator_id);
CREATE INDEX operator_logs_action_type_idx ON public.operator_logs (action_type);
CREATE INDEX operator_logs_created_at_idx  ON public.operator_logs (created_at DESC);

-- ── unidades_medida ───────────────────────────────────────────
CREATE TABLE public.unidades_medida (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome       text NOT NULL,
  abreviacao text NOT NULL,
  tipo       text NOT NULL,  -- estoque | compra | consumo
  ordem      integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

-- ── notas_fiscais / itens / entradas de estoque ───────────────
CREATE TABLE public.notas_fiscais (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  chave_acesso    text UNIQUE,
  numero          text,
  serie           text,
  data_emissao    date,
  fornecedor_nome text,
  fornecedor_cnpj text,
  valor_total     numeric,
  origem          text DEFAULT 'xml',
  status          text DEFAULT 'importada',
  xml_raw         text,
  created_at      timestamptz DEFAULT now()
);

CREATE TABLE public.notas_fiscais_itens (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nota_fiscal_id     uuid   REFERENCES public.notas_fiscais(id) ON DELETE CASCADE,
  product_id         bigint REFERENCES public.products(id) ON DELETE SET NULL,
  descricao_xml      text,
  codigo_xml         text,
  unidade_xml        text,
  quantidade         numeric,
  preco_unitario     numeric,
  preco_total        numeric,
  fator_conversao    numeric DEFAULT 1,
  quantidade_estoque numeric
);

CREATE TABLE public.estoque_entradas (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id     bigint REFERENCES public.products(id) ON DELETE CASCADE,
  nota_fiscal_id uuid   REFERENCES public.notas_fiscais(id) ON DELETE SET NULL,
  quantidade     numeric,
  preco_unitario numeric,
  data_entrada   date DEFAULT CURRENT_DATE,
  observacao     text,
  created_at     timestamptz DEFAULT now()
);

-- ── itens_fiscal (dados fiscais por produto) ──────────────────
CREATE TABLE public.itens_fiscal (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  item_id            bigint NOT NULL UNIQUE REFERENCES public.products(id) ON DELETE CASCADE,
  ncm                text,
  cest               text,
  cfop               text,
  origem_mercadoria  text,
  csosn              text,
  cst_icms           text,
  aliquota_icms      numeric DEFAULT 0,
  reducao_base_icms  numeric DEFAULT 0,
  cst_ipi            text,
  aliquota_ipi       numeric DEFAULT 0,
  cst_pis            text,
  aliquota_pis       numeric DEFAULT 0,
  cst_cofins         text,
  aliquota_cofins    numeric DEFAULT 0,
  aliquota_ibs       numeric DEFAULT 0,
  aliquota_cbs       numeric DEFAULT 0,
  aliquota_is        numeric DEFAULT 0,
  regime_tributario  text DEFAULT 'simples',
  observacao_fiscal  text,
  updated_at         timestamptz DEFAULT now()
);

-- ── subprodutos / combos ──────────────────────────────────────
CREATE TABLE public.subprodutos (
  id               uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  nome             text    NOT NULL,
  categoria        text,
  preco            numeric NOT NULL DEFAULT 0,
  unidade_medida   text,
  controla_estoque boolean NOT NULL DEFAULT false,
  ativo            boolean NOT NULL DEFAULT true,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.combos (
  id                uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  nome              text    NOT NULL,
  item_principal_id bigint  NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  modo              text    NOT NULL DEFAULT 'combo',
  preco_total       numeric,
  ativo             boolean NOT NULL DEFAULT true,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.combo_subprodutos (
  id                uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  combo_id          uuid    NOT NULL REFERENCES public.combos(id) ON DELETE CASCADE,
  subproduto_id     uuid    NOT NULL REFERENCES public.subprodutos(id),
  quantidade        integer NOT NULL DEFAULT 1,
  preco_customizado numeric,
  created_at        timestamptz NOT NULL DEFAULT now()
);

-- ── impressão (locais e roteamento por categoria) ─────────────
CREATE TABLE public.locais_impressao (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome       text NOT NULL,
  descricao  text,
  ativo      boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.categorias_roteamento (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  categoria          text NOT NULL UNIQUE,
  local_impressao_id uuid REFERENCES public.locais_impressao(id) ON DELETE SET NULL,
  updated_at         timestamptz DEFAULT now()
);

-- ── mesas (layout físico; status derivado no front) ───────────
CREATE TABLE public.mesas (
  numero        text PRIMARY KEY,
  capacidade    integer DEFAULT 4,
  posicao_x     integer,
  posicao_y     integer,
  status_manual text DEFAULT 'livre',
  created_at    timestamptz DEFAULT now(),
  updated_at    timestamptz DEFAULT now()
);

-- ── estoque (uma linha por produto — migração 20260705) ───────
CREATE TABLE public.estoque (
  produto_id bigint  PRIMARY KEY REFERENCES public.products(id) ON DELETE CASCADE,
  quantidade numeric NOT NULL DEFAULT 0 CHECK (quantidade >= 0),
  minimo     numeric NOT NULL DEFAULT 10 CHECK (minimo >= 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- ── Jarvas (eventos + insights — migração 20260703) ───────────
CREATE TABLE public.jarvas_eventos (
  id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tipo        text   NOT NULL,
  modulo      text   NOT NULL,
  payload     jsonb  NOT NULL DEFAULT '{}',
  operator_id text,
  processado  boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX jarvas_eventos_tipo_idx       ON public.jarvas_eventos (tipo);
CREATE INDEX jarvas_eventos_processado_idx ON public.jarvas_eventos (processado, created_at);
CREATE INDEX jarvas_eventos_created_at_idx ON public.jarvas_eventos (created_at DESC);

CREATE TABLE public.jarvas_insights (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tipo         text NOT NULL CHECK (tipo IN ('insight', 'alerta', 'sugestao')),
  severidade   text NOT NULL DEFAULT 'info' CHECK (severidade IN ('info', 'warning', 'danger')),
  visibilidade text NOT NULL DEFAULT 'operacional' CHECK (visibilidade IN ('operacional', 'estrategico')),
  modulo       text NOT NULL,
  titulo       text NOT NULL,
  descricao    text NOT NULL,
  acao         jsonb,
  origem       jsonb NOT NULL DEFAULT '{}',
  status       text NOT NULL DEFAULT 'novo' CHECK (status IN ('novo', 'lido', 'descartado', 'executado')),
  status_por   text,
  status_em    timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX jarvas_insights_status_idx     ON public.jarvas_insights (status, created_at DESC);
CREATE INDEX jarvas_insights_tipo_idx       ON public.jarvas_insights (tipo);
CREATE INDEX jarvas_insights_created_at_idx ON public.jarvas_insights (created_at DESC);

-- =============================================================
-- FUNÇÕES (definições completas nas migrações indicadas)
-- =============================================================
-- verificar_senha_admin(p_password text, p_username text)  → 20240106_rpc_verificar_senha.sql
-- custom_access_token_hook(event jsonb)                    → 20240105 + 20240108 (claim `role` no JWT)
-- limpar_reserva_mesa(mesa_numero text)                    → 20260702_rpc_limpar_reserva_mesa.sql
-- baixar_estoque(p_produto_id bigint, p_qtd numeric)       → 20260705_estoque_tabela.sql ; 20260712_estoque_alerta_minimo.sql
--   (SECURITY DEFINER com checagem de role caixa/gerente/admin)
--   RETURNS TABLE (quantidade numeric, minimo numeric) desde 20260712 — antes RETURNS void (F008)
-- jarvas_resumo_vendas(p_desde timestamptz, p_limite_produtos int) → 20260709_jarvas_resumo_vendas.sql
--   (agregação SQL de vendas 30d/top produtos para o assistente do Jarvas — TD009 etapa 2)
-- relatorio_vendas(p_inicio timestamptz, p_fim timestamptz, p_limite_produtos int) → 20260714_relatorio_vendas.sql
--   (faturamento/nº vendas/série diária/por método/top produtos por período — F011, Relatórios)

-- =============================================================
-- ROW LEVEL SECURITY (estado real — nomes verificados em produção)
-- Definições completas: 20240107_rls_por_role.sql, 20260701_mesas.sql,
-- 20260703_jarvas.sql, 20260705_estoque_tabela.sql
-- =============================================================
-- users                 → users_{select,insert,update,delete}_admin (só admin)
-- products              → products_select_auth ; products_write_gerente_admin
-- pending               → pending_all_auth (qualquer logado)
-- sales                 → sales_all_caixa_up (caixa/gerente/admin)
-- vendas                → vendas_all_caixa_up (caixa/gerente/admin) — TD009 etapa 1
-- venda_itens           → venda_itens_all_caixa_up (caixa/gerente/admin) — TD009 etapa 1
-- venda_pagamentos      → venda_pagamentos_all_caixa_up (caixa/gerente/admin) — TD009 etapa 1
-- fechamentos           → fechamentos_all_caixa_up (caixa/gerente/admin)
-- config                → config_select_auth ; config_write_gerente_admin
-- operator_logs         → oplogs_insert_auth ; oplogs_select_gerente_admin
-- unidades_medida       → unidades_select_auth ; unidades_write_admin
-- notas_fiscais         → nf_all_gerente_admin
-- notas_fiscais_itens   → nf_itens_all_gerente_admin
-- estoque_entradas      → estoque_all_gerente_admin
-- itens_fiscal          → itens_fiscal_all_gerente_admin
-- subprodutos           → subprodutos_select_auth ; subprodutos_write_gerente_admin
-- combos                → combos_select_auth ; combos_write_gerente_admin
-- combo_subprodutos     → combo_subs_select_auth ; combo_subs_write_gerente_admin
-- locais_impressao      → impressao_select_auth ; impressao_write_admin
-- categorias_roteamento → roteamento_select_auth ; roteamento_write_admin
-- mesas                 → mesas_select_auth ; mesas_write_gerente_admin
-- estoque               → estoque_select_auth ; estoque_{insert,update}_caixa_gerencia ; estoque_delete_gerencia
-- jarvas_eventos        → jarvas_eventos_insert_auth ; jarvas_eventos_{select,update}_gerencia
-- jarvas_insights       → jarvas_insights_select_{operacional,estrategico} ; jarvas_insights_{insert,update}_gerencia
-- lancamentos           → lancamentos_all_gerencia ; lancamentos_insert_venda_caixa (Financeiro fase 1)
-- clientes              → clientes_select_auth ; clientes_insert_update_operacional (garcom/caixa/gerente/admin) ; clientes_delete_gerencia (F010, 20260713_clientes.sql)

-- ── Realtime ──────────────────────────────────────────────────
-- Habilitado no dashboard para: pending, estoque, jarvas_insights, mesas
-- (Database → Replication → Tables)
